import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { runInNewContext } from "node:vm";
import test from "node:test";

function markdownTools() {
  const source = readFileSync(new URL("../markdown.js", import.meta.url), "utf8");
  const context = { globalThis: {} };
  runInNewContext(source, context);
  return context.globalThis.XToXhsMarkdown;
}

test("复制 Markdown 保留文本结构且过滤图片", () => {
  const markdown = markdownTools().blocksToMarkdown([
    { type: "heading", level: 1, text: "文章标题" },
    { type: "paragraph", text: "正文内容" },
    { type: "image", url: "https://pbs.twimg.com/media/example" },
    { type: "code", text: "const answer = 42;", language: "js" },
  ], { includeImages: false });

  assert.match(markdown, /^# 文章标题\n\n正文内容/u);
  assert.match(markdown, /```js\nconst answer = 42;/u);
  assert.doesNotMatch(markdown, /pbs\.twimg\.com/u);
});

test("采集器保留 X Article 的正文与懒加载兼容选择器", () => {
  const source = readFileSync(new URL("../content.js", import.meta.url), "utf8");

  assert.match(source, /p, h1, h2, h3, h4, h5, h6, li, blockquote/u);
  assert.match(source, /longform-unstyled \.public-DraftStyleDefault-block/u);
  assert.match(source, /show more\|显示更多/u);
  assert.match(source, /revealLazyContent/u);
  assert.match(source, /CODE_NODE_SELECTOR/u);
  assert.match(source, /seenCodeContainers/u);
  assert.match(source, /codeLanguageOf/u);
  assert.match(source, /articleMarker/u);
  assert.match(source, /lines\[articleMarker \+ 1\]/u);
  assert.doesNotMatch(source, /\[class\*="monospace"\].*type: "code"/su);
});

test("Manifest 保持独立运行所需的最小权限", () => {
  const manifest = JSON.parse(readFileSync(new URL("../manifest.json", import.meta.url), "utf8"));

  assert.equal(manifest.name, "x-to-md");
  assert.equal(manifest.version, "2.3.0");
  assert.deepEqual(manifest.permissions, ["activeTab", "storage", "sidePanel", "scripting"]);
  assert.deepEqual(manifest.side_panel, { default_path: "sidepanel.html" });
  assert.equal(manifest.action.default_popup, undefined);
  assert.equal(manifest.background.service_worker, "background.js");
  assert.equal(manifest.web_accessible_resources, undefined);
  const background = readFileSync(new URL("../background.js", import.meta.url), "utf8");
  assert.match(background, /toggle-candidate-overlay/u);
  assert.match(background, /chrome\.sidePanel\.open/u);
  assert.match(background, /chrome\.sidePanel\.open\(\{ windowId: tab\.windowId \}\)\.catch/u);
  assert.match(background, /chrome\.sidePanel\.open\([\s\S]+?ensureContentScript\(tab\)\.catch/u);
  assert.match(background, /ensureContentScript/u);
  assert.match(background, /chrome\.scripting\.executeScript/u);
  assert.match(background, /if \(ready\?\.ok\) return;/u);
  assert.match(background, /files: \["markdown\.js", "content\.js"\]/u);
  assert.match(background, /injectOpenXTabs/u);
  assert.match(background, /chrome\.runtime\.onInstalled/u);
  assert.match(background, /chrome\.runtime\.onStartup/u);
});

test("Content Inbox 提供上下文感知收件箱、关注作者和素材库 Side Panel", () => {
  const html = readFileSync(new URL("../sidepanel.html", import.meta.url), "utf8");
  const script = readFileSync(new URL("../sidepanel.js", import.meta.url), "utf8");
  const css = readFileSync(new URL("../sidepanel.css", import.meta.url), "utf8");
  const content = readFileSync(new URL("../content.js", import.meta.url), "utf8");

  assert.match(html, /收件箱/u);
  assert.match(html, /关注作者/u);
  assert.match(html, /素材库/u);
  assert.match(html, /current-context/u);
  assert.doesNotMatch(script, /discover-articles/u);
  assert.match(script, /Receiving end does not exist/u);
  assert.match(script, /tabs\.reload\(tab\.id\)/u);
  assert.match(script, /无法连接当前 X 页面/u);
  assert.match(script, /chrome\.storage\.local/u);
  assert.match(script, /chrome\.storage\.onChanged/u);
  assert.match(script, /loadData\(\)\.then\(\(\) => render\(\)\)/u);
  assert.match(script, /candidateSort: "addedAt"/u);
  assert.match(script, /data-candidate-sort="addedAt"/u);
  assert.match(script, /data-candidate-sort="publishedAt"/u);
  assert.match(script, /sortedCandidates/u);
  assert.match(content, /const addedAt = new Date\(\)\.toISOString\(\)/u);
  assert.match(script, /新发现/u);
  assert.match(script, /已保存素材/u);
  assert.match(script, /coverImageUrl/u);
  assert.match(script, /authorAvatarUrl/u);
  assert.match(script, /candidatePreviews/u);
  assert.match(script, /class="author-cell"/u);
  assert.match(script, /class="author-profile-link"/u);
  assert.match(script, /https:\/\/x\.com\/\$\{String\(subscription\.handle/u);
  assert.match(script, /target="_blank" rel="noreferrer" aria-label="Open/u);
  assert.match(script, /class="follow-button is-following"/u);
  assert.match(script, />Following</u);
  assert.match(script, />unfollow</u);
  assert.match(script, /subscription-unfollow/u);
  assert.doesNotMatch(script, /subscription-(?:open|toggle|edit|delete)/u);
  assert.doesNotMatch(script, /addSubscription|renderSubscriptionDetail|fetchArticles/u);
  assert.doesNotMatch(content, /discover-articles/u);
  assert.match(content, /authorPresentationFromElement/u);
  assert.match(content, /normalizedIdentity/u);
  assert.match(content, /descriptionCandidates/u);
  assert.match(content, /!node\.closest\('a\[href\]'\)/u);
  assert.match(content, /!node\.querySelector\('div\[dir="auto"\]'\)/u);
  assert.match(content, /description: author\.description/u);
  assert.match(content, /authorVerified: author\.authorVerified/u);
  assert.match(content, /existingSubscription/u);
  assert.match(script, /class="verified-badge"/u);
  assert.match(script, /aria-label="Verified account"/u);
  assert.doesNotMatch(script, /tokenStyle/u);
  assert.match(script, /xIcon/u);
  assert.doesNotMatch(script, /style="\$\{tokenStyle/u);
  assert.match(content, /article-cover-image/u);
  assert.match(content, /currentPageContext/u);
  assert.match(content, /pageKind: "article"/u);
  assert.match(content, /pageKind: "author-articles"/u);
  assert.match(content, /get-current-context/u);
  assert.doesNotMatch(content, /currentPageContext[\s\S]{0,500}content:/u);
  assert.doesNotMatch(content, /articlePresentationTokens/u);
  assert.match(script, /article-engagement/u);
  assert.match(script, /添加至素材库/u);
  assert.match(script, /candidate-save/u);
  assert.doesNotMatch(script, /在 X 中原样预览/u);
  assert.doesNotMatch(script, /open-native-article-preview/u);
  assert.doesNotMatch(script, /previewCandidateOnX/u);
  assert.doesNotMatch(readFileSync(new URL("../background.js", import.meta.url), "utf8"), /open-native-preview/u);
  assert.match(script, /candidateQuery: ""/u);
  assert.match(script, /candidateDate: "today"/u);
  assert.match(script, /搜索收件箱/u);
  assert.match(script, /data-candidate-date="today"/u);
  assert.match(script, /data-candidate-date="yesterday"/u);
  assert.match(script, /data-candidate-date="thisWeek"/u);
  assert.match(script, /data-candidate-date="lastWeek"/u);
  assert.match(script, /data-candidate-date="thisMonth"/u);
  assert.match(script, /timestamp\(candidate\.addedAt\)/u);
  assert.doesNotMatch(script, /data-candidate-date-input|type="month"/u);
  assert.match(script, /收件箱总数/u);
  assert.match(script, /candidate-chart/u);
  assert.match(script, /chart-line/u);
  assert.match(script, /candidateMatchesQuery/u);
  assert.match(script, /当前筛选条件下没有匹配的 Article/u);
  assert.match(script, /candidate-menu/u);
  assert.match(script, /candidate\.status !== "ignored" && candidate\.status !== "saved"/u);
  assert.match(script, /请先打开此候选的 X 原文/u);
  assert.match(script, /复制 Markdown/u);
  assert.match(script, /保存并复制 Markdown/u);
  assert.match(script, /context-save/u);
  assert.doesNotMatch(script, /context-scan/u);
  assert.match(script, /refreshContext/u);
  assert.match(script, /get-current-context/u);
  assert.doesNotMatch(script, /保存当前提取/u);
  assert.match(script, /删除素材/u);
  assert.match(css, /53px/u);
  assert.match(css, /--twitter-color-text-primary: rgb\(15, 20, 25\)/u);
  assert.match(css, /--twitter-color-text-secondary: rgb\(83, 100, 113\)/u);
  assert.match(css, /--twitter-color-brand: rgb\(29, 155, 240\)/u);
  assert.match(css, /--twitter-color-destructive: rgb\(244, 33, 46\)/u);
  assert.match(css, /--twitter-avatar-size: 40px/u);
  assert.match(css, /\.follow-button:hover/u);
  assert.match(css, /\.author-profile-link/u);
  assert.match(css, /aspect-ratio: var\(--article-media-ratio/u);
  assert.doesNotMatch(script, /presentation\?\.tokens/u);
  assert.doesNotMatch(script, /--article-icon-size/u);
  assert.match(css, /\.candidate-menu/u);
  assert.match(css, /\.candidate-sort/u);
  assert.match(css, /border-bottom: 1px solid var\(--x-border\)/u);
});

test("Popup 与预览页保留清晰的成功、边界和来源反馈", () => {
  const popup = readFileSync(new URL("../popup.html", import.meta.url), "utf8");
  const popupScript = readFileSync(new URL("../popup.js", import.meta.url), "utf8");
  const preview = readFileSync(new URL("../preview.html", import.meta.url), "utf8");
  const previewScript = readFileSync(new URL("../preview.js", import.meta.url), "utf8");

  assert.match(popup, /Copy the current X content as Markdown\. Nothing is uploaded\./u);
  assert.match(popup, /Extract and copy/u);
  assert.match(popup, /Nothing is uploaded/u);
  assert.match(popup, /class="description"/u);
  assert.match(popup, /class="popup-card"/u);
  assert.match(popup, /--x-color-primary/u);
  assert.match(popup, /--x-radius-panel/u);
  assert.match(popup, /--x-radius-pill/u);
  assert.match(popup, /#status:empty/u);
  assert.match(popupScript, /capture\?\.error/u);
  assert.match(popupScript, /window\.close\(\)/u);
  assert.match(popupScript, /Markdown copied\./u);
  assert.match(preview, /Extracted · Markdown copied/u);
  assert.match(preview, /class="preview-heading"/u);
  assert.match(previewScript, /View original/u);
  assert.match(previewScript, /Images are excluded from Markdown/u);
  assert.match(previewScript, /This preview has expired/u);
  assert.match(previewScript, /data-code-copy/u);
  assert.match(previewScript, /Code copied/u);
  assert.doesNotMatch(popupScript, /open-native-preview/u);
  const contentScript = readFileSync(new URL("../content.js", import.meta.url), "utf8");
  assert.match(contentScript, /Copy the current X content as Markdown\. Nothing is uploaded\./u);
  assert.doesNotMatch(contentScript, /root\.querySelectorAll\('button, \[role="button"\]\)/u);
  assert.doesNotMatch(contentScript, /message\?\.type !== "open-native-preview"/u);
  assert.match(contentScript, /toggle-import-panel/u);
  assert.match(contentScript, /toggle-candidate-overlay/u);
  assert.match(contentScript, /x-to-md-ready/u);
  assert.match(contentScript, /toggleCandidateOverlay/u);
  assert.match(contentScript, /restoreCandidateOverlay/u);
  assert.match(contentScript, /articleCandidateFromListRoot\(root\)/u);
  assert.match(contentScript, /x-to-md-candidate-overlay/u);
  assert.match(contentScript, /x-to-md-import-panel/u);
  assert.match(contentScript, /x-to-md-bookmark-candidate-toolbar/u);
  assert.match(contentScript, /x-to-md-follow-subscription-toolbar/u);
  assert.match(contentScript, />Follow<\/button>/u);
  assert.match(contentScript, /添加至收件箱/u);
  assert.match(contentScript, /从收件箱移除/u);
  assert.match(contentScript, /articleCandidateFromPage/u);
  assert.match(contentScript, /articleCandidateFromListRoot/u);
  assert.match(contentScript, /articleCardRootFromTarget/u);
  assert.match(contentScript, /article-cover-image/u);
  assert.match(contentScript, /\(\?:status\|\(\?:i\\\/\)\?article\)/u);
  assert.match(contentScript, /isArticleSourcePage/u);
  assert.match(contentScript, /articleCandidateFromPage\(\)/u);
  assert.match(contentScript, /articleCandidateFromBookmarkButton/u);
  assert.match(contentScript, /button\[data-testid="bookmark"\]/u);
  assert.match(contentScript, /button\[data-testid="removeBookmark"\]/u);
  assert.match(contentScript, /cover\?\.querySelector\("img"\)/u);
  assert.match(contentScript, /isArticlesIndexPage/u);
  assert.match(contentScript, /bookmarkButton\.getBoundingClientRect/u);
  assert.match(contentScript, /rect\.left - rect\.width - gap/u);
  assert.match(contentScript, /rect\.right \+ gap/u);
  assert.match(contentScript, /Untitled Article/u);
  assert.match(contentScript, /data-toggle-inbox-candidate/u);
  assert.match(contentScript, /isActiveInboxCandidate/u);
  assert.match(contentScript, /matchesInboxCandidate/u);
  assert.match(contentScript, /addInboxCandidate/u);
  assert.match(contentScript, /removeInboxCandidate/u);
  assert.match(contentScript, /\["ignored", "saved"\]\.includes/u);
  assert.match(contentScript, /status: "new", addedAt/u);
  assert.match(contentScript, /aria-pressed="\$\{isInInbox\}"/u);
  assert.match(contentScript, /button\.is-in-inbox:hover/u);
  assert.match(contentScript, /M4 4\.5C4 3\.12 5\.119 2 6\.5 2h11/u);
  assert.doesNotMatch(contentScript, /data-add-selection-subscription/u);
  assert.match(contentScript, /data-toggle-follow-subscription/u);
  assert.match(contentScript, /background: #1D9BF0 !important/u);
  assert.match(contentScript, /color: #FFFFFF !important/u);
  assert.match(contentScript, /data-testid="HoverCard"/u);
  assert.match(contentScript, /positionBookmarkCandidateToolbar/u);
  assert.match(contentScript, /width: 18\.75px !important/u);
  assert.doesNotMatch(contentScript, /selectionchange/u);
  assert.doesNotMatch(contentScript, /MutationObserver/u);
  assert.match(contentScript, /profileHandleFromHref/u);
  assert.match(contentScript, /normalizedHandleText/u);
  assert.match(contentScript, /\\u200B-\\u200F\\u2060\\uFEFF/u);
  assert.match(contentScript, /bookmarkCandidateState/u);
  assert.match(contentScript, /scheduleRemoveBookmarkCandidateToolbar/u);
  assert.match(contentScript, /closest\('a\[href\]'\)/u);
  assert.match(contentScript, /articleLinks\.length === 1 && coverCount <= 1/u);
  assert.match(contentScript, /root\.querySelectorAll\?\.\('\[data-testid="article-cover-image"\]'\)/u);
  assert.match(contentScript, /followButtonFromTarget/u);
  assert.match(contentScript, /authorFromFollowButton/u);
  assert.match(contentScript, /positionFollowSubscriptionToolbar/u);
  assert.match(contentScript, /Follow\|Following\|Unfollow/u);
  assert.match(contentScript, /button\.matches\('\[data-testid\$="-follow"\]'/u);
  assert.match(contentScript, /button\.matches\('\[data-testid\$="-unfollow"\]'/u);
  assert.match(contentScript, /removeAuthorSubscription/u);
  assert.match(contentScript, /data-toggle-follow-subscription/u);
  assert.match(contentScript, />Following</u);
  assert.match(contentScript, />unfollow</u);
  assert.match(contentScript, /rgb\(244, 33, 46\)/u);
  assert.match(contentScript, /location\.pathname/u);
  assert.match(contentScript, /CONTENT_INBOX_STORAGE_KEY/u);
  assert.doesNotMatch(contentScript, /document\.addEventListener\("mouseup"/u);
  assert.doesNotMatch(contentScript, /document\.addEventListener\("pointerup"/u);
  assert.match(contentScript, /document\.addEventListener\("pointerover"/u);
  assert.match(contentScript, /document\.addEventListener\("focusin"/u);
  assert.doesNotMatch(contentScript, /authorLink\.closest\('\[data-testid="User-Name"\]'\)/u);
  assert.match(contentScript, /--twitter-color-background/u);
  assert.match(contentScript, /width: 300px !important; padding: 20px !important/u);
  assert.match(contentScript, /height: 46px !important; min-height: 46px !important/u);
  assert.match(contentScript, /align-items: center !important; justify-content: center !important/u);
  assert.match(contentScript, /text-align: center !important; white-space: nowrap !important/u);
  assert.match(popup, /align-items: center; justify-content: center/u);
  assert.doesNotMatch(contentScript, /已复制 Markdown，并进入 X 原生预览/u);
});
